// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Title  string `json:"title"`
	Author *User  `json:"author"`
}

type NewArticle struct {
	ID     *string  `json:"id"`
	Text   string   `json:"text"`
	Author *NewUser `json:"author"`
	Title  string   `json:"title"`
}

type NewUser struct {
	ID    *string `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
}

type PageInfo struct {
	StartCursor *string `json:"startCursor"`
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
