// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line base.qtpl:1
package templates

//line base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line base.qtpl:2
type Page interface {
//line base.qtpl:2
	Title() string
//line base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line base.qtpl:2
	Body() string
//line base.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line base.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line base.qtpl:2
}

// Page prints a page implementing Page interface.

//line base.qtpl:10
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line base.qtpl:10
	qw422016.N().S(`
<html>
	<head>
		<title>`)
//line base.qtpl:13
	p.StreamTitle(qw422016)
//line base.qtpl:13
	qw422016.N().S(`</title>
	</head>
	<body>
		<div>
			<a href="/">return to main page</a>
		</div>
		`)
//line base.qtpl:19
	p.StreamBody(qw422016)
//line base.qtpl:19
	qw422016.N().S(`
	</body>
</html>
`)
//line base.qtpl:22
}

//line base.qtpl:22
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line base.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line base.qtpl:22
	StreamPageTemplate(qw422016, p)
//line base.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:22
}

//line base.qtpl:22
func PageTemplate(p Page) string {
//line base.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line base.qtpl:22
	WritePageTemplate(qb422016, p)
//line base.qtpl:22
	qs422016 := string(qb422016.B)
//line base.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line base.qtpl:22
	return qs422016
//line base.qtpl:22
}

// Base page implementation. Other pages may inherit from it if they need
// overriding only certain Page methods

//line base.qtpl:27
type BasePage struct{}

//line base.qtpl:28
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line base.qtpl:28
	qw422016.N().S(`This is a base title`)
//line base.qtpl:28
}

//line base.qtpl:28
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line base.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line base.qtpl:28
	p.StreamTitle(qw422016)
//line base.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:28
}

//line base.qtpl:28
func (p *BasePage) Title() string {
//line base.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line base.qtpl:28
	p.WriteTitle(qb422016)
//line base.qtpl:28
	qs422016 := string(qb422016.B)
//line base.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line base.qtpl:28
	return qs422016
//line base.qtpl:28
}

//line base.qtpl:29
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line base.qtpl:29
	qw422016.N().S(`This is a base body`)
//line base.qtpl:29
}

//line base.qtpl:29
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line base.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line base.qtpl:29
	p.StreamBody(qw422016)
//line base.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:29
}

//line base.qtpl:29
func (p *BasePage) Body() string {
//line base.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line base.qtpl:29
	p.WriteBody(qb422016)
//line base.qtpl:29
	qs422016 := string(qb422016.B)
//line base.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line base.qtpl:29
	return qs422016
//line base.qtpl:29
}
