// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line index.qtpl:1
package templates

//line index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:1
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line index.qtpl:1
	qw422016.N().S(`
	This is the main page
`)
//line index.qtpl:3
}

//line index.qtpl:3
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line index.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.qtpl:3
	p.StreamTitle(qw422016)
//line index.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:3
}

//line index.qtpl:3
func (p *MainPage) Title() string {
//line index.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line index.qtpl:3
	p.WriteTitle(qb422016)
//line index.qtpl:3
	qs422016 := string(qb422016.B)
//line index.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line index.qtpl:3
	return qs422016
//line index.qtpl:3
}

//line index.qtpl:5
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line index.qtpl:5
	qw422016.N().S(`
	<h1>Main page</h1>
	<div>
		Click links below:
		<ul>
			<li><a href="/table?rowsCount=42">Table page</a></li>
			<li><a href="/unknown-page">Error page</a></li>
		</ul>
	</div>
	<div>
		Some info about you:<br/>
		IP: <b>`)
//line index.qtpl:16
	qw422016.E().S(p.CTX.RemoteIP().String())
//line index.qtpl:16
	qw422016.N().S(`</b><br/>
		User-Agent: <b>`)
//line index.qtpl:17
	qw422016.E().Z(p.CTX.UserAgent())
//line index.qtpl:17
	qw422016.N().S(`</b><br/>
	</div>
`)
//line index.qtpl:19
}

//line index.qtpl:19
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line index.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.qtpl:19
	p.StreamBody(qw422016)
//line index.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:19
}

//line index.qtpl:19
func (p *MainPage) Body() string {
//line index.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line index.qtpl:19
	p.WriteBody(qb422016)
//line index.qtpl:19
	qs422016 := string(qb422016.B)
//line index.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line index.qtpl:19
	return qs422016
//line index.qtpl:19
}
